name: Stock Data Automation

on:
  schedule:
    # Run at 2:00 AM UTC daily (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/**.yml'

jobs:
  download-stock-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run stock data download
      run: python main.py
      env:
        OUTPUT_DIR: data
        
    - name: Check generated files
      run: |
        echo "Generated files:"
        ls -la data/
        echo "TA125 CSV rows:"
        wc -l data/Shazam-Stock-Info-TA125.csv || echo "TA125 file not found"
        echo "SP500 CSV rows:"
        wc -l data/Shazam-Stock-Info-SP500.csv || echo "SP500 file not found"
        
    - name: Commit and push CSV files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*.csv data/*.json
        git diff --staged --quiet || git commit -m "Update stock data - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload CSV files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: stock-data-csv
        path: |
          data/Shazam-Stock-Info-TA125.csv
          data/Shazam-Stock-Info-SP500.csv
          data/download_status.json
        retention-days: 30